// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SebastianCoetzee/blog-order-service-example/clients/restaurant (interfaces: Client)

// Package mock_restaurant is a generated GoMock package.
package mock_restaurant

import (
	models "github.com/SebastianCoetzee/blog-order-service-example/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetRestaurantsByIDs mocks base method
func (m *MockClient) GetRestaurantsByIDs(arg0 []int) (models.Restaurants, error) {
	ret := m.ctrl.Call(m, "GetRestaurantsByIDs", arg0)
	ret0, _ := ret[0].(models.Restaurants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantsByIDs indicates an expected call of GetRestaurantsByIDs
func (mr *MockClientMockRecorder) GetRestaurantsByIDs(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantsByIDs", reflect.TypeOf((*MockClient)(nil).GetRestaurantsByIDs), arg0)
}
